version: '3.1'

services:
  db:
    build: ./postgres
    ports:
      - "5433:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data


  web:
    build: ./flask_app
    ports:
      - "5001:5001"
    depends_on:
      - db

volumes:
  db_data: {}
